spring:
  ai:
    model:
      embedding: ollama
      chat: ollama
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          temperature: 0.7
          model: qwen3:4b
#        model: qwen3:4b # 和options.model中的效果一样
      embedding:
        model: nomic-embed-text:latest
      init:
        pull-model-strategy: when_missing
        embedding:
          include: true
    vectorstore:
      redis:
        initialize-schema: true
        index-name: ollama-index
        prefix: custom-prefix
  application:
    name: ollama-rag
  config:
    import: nacos:nacos-config.properties
  cloud:
    nacos:
      config:
        file-extension: properties
        name: nacos-config
        username: nacos
        password: nacos
        namespace: d7da1cc0-7ed5-43a6-9a4e-d32edb8b6043
        server-addr: localhost:8848
  data:
    redis:
      host: localhost
      port: 6379