spring:
  ai:
    mcp:
      server:
        enabled: true
        sse-message-endpoint: /mcp/message
        type: sync
        tool-change-notification: false
        prompt-change-notification: false
        resource-change-notification: false
